script:
  - "npm run travis"

language: node_js

node_js:
  - "0.12"

branches:
  only:
    - master
    - dev

matrix:
  fast_finish: true
  include:
    - env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
